String s1= 'abcd';
String s2 = 'efgh';
Integer s3 = s1.compareTo(s2);
system.debug('here is '+s3); //-4

String s4 = 'abef';
String s5 = 'cdgh';
Integer s6= s4.compareTo(s5);
System.debug (s6); //-2


String myName = 'shelley doty';
Integer Inn= myName.indexOf('ll');
System.debug('inn =  '+Inn); //3?

//contains excercise

String name1 = 'shelley';
String name2 = 'hello';
System.debug('using contains method '+name1.contains('ell') );

